In [1]:
from pathlib import Path
import shutil
import csv
import numpy as np
import pandas as pd
import json

In [8]:
path_full_img = Path('../final_dataset/test/images')
path_full_labels = Path('../final_dataset/test/labels')
path_test_img = Path('../lite_dataset/test/images')
path_test_labels = Path('../lite_dataset/test/labels')

In [11]:
if not path_test_img.exists() and not path_test_labels.exists():
    try:
        path_test_img.mkdir(parents=True)
        path_test_labels.mkdir()
        print('Path test dataset created!')
    except Exception as e:
        print('Path test dataset creation failed!' , e)

Path test dataset created!

In [12]:
# copy img and labels file to test folder
# where TEST_NUM is number of files
TEST_NUM = 200
itr = 1
for file in path_full_img.glob('*.jpg'):
    print(itr,'   ',file)
    label_path= Path(path_full_labels,file.stem+'.txt')
    shutil.copy(file, path_test_img)
    shutil.copy(label_path, path_test_labels)
    print(label_path)
    
    
    if itr >= TEST_NUM:
        break
    itr += 1

1     ..\final_dataset\test\images\000106393cfe2343888c584e65fd2274.jpg
..\final_dataset\test\labels\000106393cfe2343888c584e65fd2274.txt
2     ..\final_dataset\test\images\0039eb1ff33d29c55f943e05730bb259.jpg
..\final_dataset\test\labels\0039eb1ff33d29c55f943e05730bb259.txt
3     ..\final_dataset\test\images\0041e69431bf872309d1aff628b6494f.jpg
..\final_dataset\test\labels\0041e69431bf872309d1aff628b6494f.txt
4     ..\final_dataset\test\images\0049943dd024c06611a90feb5acebbbd.jpg
..\final_dataset\test\labels\0049943dd024c06611a90feb5acebbbd.txt
5     ..\final_dataset\test\images\009a5b410ff34d171280c1135e15c011.jpg
..\final_dataset\test\labels\009a5b410ff34d171280c1135e15c011.txt
6     ..\final_dataset\test\images\00b627cb5578bb036edb01cdcf7b56d9.jpg
..\final_dataset\test\labels\00b627cb5578bb036edb01cdcf7b56d9.txt
7     ..\final_dataset\test\images\011ced9d123e0da9c289e94a3b11165e.jpg
..\final_dataset\test\labels\011ced9d123e0da9c289e94a3b11165e.txt
8     ..\final_dataset\test\images\012da930e0406f7ffe8e0f3af74fed0e.jpg
..\final_dataset\test\labels\012da930e0406f7ffe8e0f3af74fed0e.txt
9     ..\final_dataset\test\images\0173b9cb6de97440d92705a5369857dc.jpg
..\final_dataset\test\labels\0173b9cb6de97440d92705a5369857dc.txt
10     ..\final_dataset\test\images\01a9523f09174abae4f2b63e52a99482.jpg
..\final_dataset\test\labels\01a9523f09174abae4f2b63e52a99482.txt
11     ..\final_dataset\test\images\01bcd847232dd6d65ed07606fd537400.jpg
..\final_dataset\test\labels\01bcd847232dd6d65ed07606fd537400.txt
12     ..\final_dataset\test\images\01c2435888ca6cb8e59eaf199d85b608.jpg
..\final_dataset\test\labels\01c2435888ca6cb8e59eaf199d85b608.txt
13     ..\final_dataset\test\images\01fc41e0e2a068bdb46341bea333cd1c.jpg
..\final_dataset\test\labels\01fc41e0e2a068bdb46341bea333cd1c.txt
14     ..\final_dataset\test\images\01fcc92616f43f46c5356f82eb1e9b77.jpg
..\final_dataset\test\labels\01fcc92616f43f46c5356f82eb1e9b77.txt
15     ..\final_dataset\test\images\0219f152494be3d3caa07264ad61887e.jpg
..\final_dataset\test\labels\0219f152494be3d3caa07264ad61887e.txt
16     ..\final_dataset\test\images\023b32ea680c00d59c34f254b87400f6.jpg
..\final_dataset\test\labels\023b32ea680c00d59c34f254b87400f6.txt
17     ..\final_dataset\test\images\023cc897edc78f676fd1f2f347d80e83.jpg
..\final_dataset\test\labels\023cc897edc78f676fd1f2f347d80e83.txt
18     ..\final_dataset\test\images\024935fca7e34a4ffd001a205eadbe58.jpg
..\final_dataset\test\labels\024935fca7e34a4ffd001a205eadbe58.txt
19     ..\final_dataset\test\images\0264281592520685b7c6505d2819769f.jpg
..\final_dataset\test\labels\0264281592520685b7c6505d2819769f.txt
20     ..\final_dataset\test\images\0266d078bb467076817b8e7c58490a46.jpg
..\final_dataset\test\labels\0266d078bb467076817b8e7c58490a46.txt
21     ..\final_dataset\test\images\0270ff077bad1a1be7eb92a0e82cd107.jpg
..\final_dataset\test\labels\0270ff077bad1a1be7eb92a0e82cd107.txt
22     ..\final_dataset\test\images\02734fcb986f51711325d049ec55d14e.jpg
..\final_dataset\test\labels\02734fcb986f51711325d049ec55d14e.txt
23     ..\final_dataset\test\images\02785b7f8e63e54cc31aa80accc6e590.jpg
..\final_dataset\test\labels\02785b7f8e63e54cc31aa80accc6e590.txt
24     ..\final_dataset\test\images\0285d1b04f2c55e90f78a072446e4fd3.jpg
..\final_dataset\test\labels\0285d1b04f2c55e90f78a072446e4fd3.txt
25     ..\final_dataset\test\images\029951993b9278dbc2f7f88755d79d7b.jpg
..\final_dataset\test\labels\029951993b9278dbc2f7f88755d79d7b.txt
26     ..\final_dataset\test\images\02a0a447a3bcc9cf947e149f881eaf9a.jpg
..\final_dataset\test\labels\02a0a447a3bcc9cf947e149f881eaf9a.txt
27     ..\final_dataset\test\images\02c66bc41180665edf37ff4caf7bc1e4.jpg
..\final_dataset\test\labels\02c66bc41180665edf37ff4caf7bc1e4.txt
28     ..\final_dataset\test\images\02df5f88c2dd366113aa6abc906e8b83.jpg
..\final_dataset\test\labels\02df5f88c2dd366113aa6abc906e8b83.txt
29     ..\final_dataset\test\images\0366e9b9b25ca38d17fda3eb0032b009.jpg
..\final_dataset\test\labels\0366e9b9b25ca38d17fda3eb0032b009.txt
30     ..\final_dataset\test\images\0397c5392ba5190f798fe04de92d52dc.jpg
..\final_dataset\test\labels\0397c5392ba5190f798fe04de92d52dc.txt
31     ..\final_dataset\test\images\03b84839ca5a7fa48209f714241b6ef5.jpg
..\final_dataset\test\labels\03b84839ca5a7fa48209f714241b6ef5.txt
32     ..\final_dataset\test\images\03bee5224965f2d87bd397b7ddd50875.jpg
..\final_dataset\test\labels\03bee5224965f2d87bd397b7ddd50875.txt
33     ..\final_dataset\test\images\03cb9dd1710ef0eb165be3ff44b8ef70.jpg
..\final_dataset\test\labels\03cb9dd1710ef0eb165be3ff44b8ef70.txt
34     ..\final_dataset\test\images\03e7dd6896f2169a2a94344b0b2fc254.jpg
..\final_dataset\test\labels\03e7dd6896f2169a2a94344b0b2fc254.txt
35     ..\final_dataset\test\images\03f7bc02b925509cb507d2f4b9725e4e.jpg
..\final_dataset\test\labels\03f7bc02b925509cb507d2f4b9725e4e.txt
36     ..\final_dataset\test\images\04170bd2af2b63d2a7df5bc4e6be7a51.jpg
..\final_dataset\test\labels\04170bd2af2b63d2a7df5bc4e6be7a51.txt
37     ..\final_dataset\test\images\043ddd1cc154aefeeb4b57c9b2e56982.jpg
..\final_dataset\test\labels\043ddd1cc154aefeeb4b57c9b2e56982.txt
38     ..\final_dataset\test\images\044425a07b59ca9b0f128f4f54eacc9a.jpg
..\final_dataset\test\labels\044425a07b59ca9b0f128f4f54eacc9a.txt
39     ..\final_dataset\test\images\0452c8bd37594601465039eb424bf294.jpg
..\final_dataset\test\labels\0452c8bd37594601465039eb424bf294.txt
40     ..\final_dataset\test\images\045bf96a1debb70f997e817e2fd46a1c.jpg
..\final_dataset\test\labels\045bf96a1debb70f997e817e2fd46a1c.txt
41     ..\final_dataset\test\images\0464dd1a30aaf3fcb58646d85fb3c044.jpg
..\final_dataset\test\labels\0464dd1a30aaf3fcb58646d85fb3c044.txt
42     ..\final_dataset\test\images\0466439003f7b9214a3a15bde1831e3b.jpg
..\final_dataset\test\labels\0466439003f7b9214a3a15bde1831e3b.txt
43     ..\final_dataset\test\images\047cc850b8d18427ce24e77b766d14db.jpg
..\final_dataset\test\labels\047cc850b8d18427ce24e77b766d14db.txt
44     ..\final_dataset\test\images\048831fe15e2938828b9316fa978cbc3.jpg
..\final_dataset\test\labels\048831fe15e2938828b9316fa978cbc3.txt
45     ..\final_dataset\test\images\04a3d479d3aaf701476a705526bde6ee.jpg
..\final_dataset\test\labels\04a3d479d3aaf701476a705526bde6ee.txt
46     ..\final_dataset\test\images\04a73f4f1bde123f42e5a9240be9eb0e.jpg
..\final_dataset\test\labels\04a73f4f1bde123f42e5a9240be9eb0e.txt
47     ..\final_dataset\test\images\04ae480f61539d26f8b45fdb4714226d.jpg
..\final_dataset\test\labels\04ae480f61539d26f8b45fdb4714226d.txt
48     ..\final_dataset\test\images\04cefb66f077ecec12f617e751697d3f.jpg
..\final_dataset\test\labels\04cefb66f077ecec12f617e751697d3f.txt
49     ..\final_dataset\test\images\04f96296dc4e450031042387d3eddf6e.jpg
..\final_dataset\test\labels\04f96296dc4e450031042387d3eddf6e.txt
50     ..\final_dataset\test\images\04fe842dda2e9fd25e75cef5d12b38a0.jpg
..\final_dataset\test\labels\04fe842dda2e9fd25e75cef5d12b38a0.txt
51     ..\final_dataset\test\images\050a9b7530e2e02211ee387f0e528dec.jpg
..\final_dataset\test\labels\050a9b7530e2e02211ee387f0e528dec.txt
52     ..\final_dataset\test\images\050b54dee22d97329b7355d9ecff4f47.jpg
..\final_dataset\test\labels\050b54dee22d97329b7355d9ecff4f47.txt
53     ..\final_dataset\test\images\0560e20e68dac2114517822a25ee31f4.jpg
..\final_dataset\test\labels\0560e20e68dac2114517822a25ee31f4.txt
54     ..\final_dataset\test\images\057e708755395a051d98fa7398c0cac3.jpg
..\final_dataset\test\labels\057e708755395a051d98fa7398c0cac3.txt
55     ..\final_dataset\test\images\058476b6a76ef809ac7c381f52666322.jpg
..\final_dataset\test\labels\058476b6a76ef809ac7c381f52666322.txt
56     ..\final_dataset\test\images\058c36a1f3c52872ae56cbf9efba3cd7.jpg
..\final_dataset\test\labels\058c36a1f3c52872ae56cbf9efba3cd7.txt
57     ..\final_dataset\test\images\058dee5bdcf0c13c2ac1a334f59ecce7.jpg
..\final_dataset\test\labels\058dee5bdcf0c13c2ac1a334f59ecce7.txt
58     ..\final_dataset\test\images\059338d7fb2c2ce8cdb52d0e2fc6f002.jpg
..\final_dataset\test\labels\059338d7fb2c2ce8cdb52d0e2fc6f002.txt
59     ..\final_dataset\test\images\059843e8192d9e4e990da370775e1b53.jpg
..\final_dataset\test\labels\059843e8192d9e4e990da370775e1b53.txt
60     ..\final_dataset\test\images\0599a768519c3fcf30d0dad2545fe7c7.jpg
..\final_dataset\test\labels\0599a768519c3fcf30d0dad2545fe7c7.txt
61     ..\final_dataset\test\images\05a3597048d08814796898b453f571b4.jpg
..\final_dataset\test\labels\05a3597048d08814796898b453f571b4.txt
62     ..\final_dataset\test\images\05ef1b83fab31eb6a2547c1b5c901873.jpg
..\final_dataset\test\labels\05ef1b83fab31eb6a2547c1b5c901873.txt
63     ..\final_dataset\test\images\0619bf8396a765a73f7a2b8f7d04acae.jpg
..\final_dataset\test\labels\0619bf8396a765a73f7a2b8f7d04acae.txt
64     ..\final_dataset\test\images\061c66250967a10ca840c00d844839cc.jpg
..\final_dataset\test\labels\061c66250967a10ca840c00d844839cc.txt
65     ..\final_dataset\test\images\0627eb82806e0e3cb3bd229a1572b69b.jpg
..\final_dataset\test\labels\0627eb82806e0e3cb3bd229a1572b69b.txt
66     ..\final_dataset\test\images\06343ae4bc2051dc5993b723a30215a5.jpg
..\final_dataset\test\labels\06343ae4bc2051dc5993b723a30215a5.txt
67     ..\final_dataset\test\images\065277d6aed4a22439c9926f7df8b097.jpg
..\final_dataset\test\labels\065277d6aed4a22439c9926f7df8b097.txt
68     ..\final_dataset\test\images\0677f183db212e98c1503f73f32cdb33.jpg
..\final_dataset\test\labels\0677f183db212e98c1503f73f32cdb33.txt
69     ..\final_dataset\test\images\06b9198f251d64f43dc7cee13fc91332.jpg
..\final_dataset\test\labels\06b9198f251d64f43dc7cee13fc91332.txt
70     ..\final_dataset\test\images\06bf5da72d927d021d784e8c37cece4c.jpg
..\final_dataset\test\labels\06bf5da72d927d021d784e8c37cece4c.txt
71     ..\final_dataset\test\images\06c47f77e389d8461799b219559b2c61.jpg
..\final_dataset\test\labels\06c47f77e389d8461799b219559b2c61.txt
72     ..\final_dataset\test\images\07036a2bab3c2b6c594df2ff11933fe5.jpg
..\final_dataset\test\labels\07036a2bab3c2b6c594df2ff11933fe5.txt
73     ..\final_dataset\test\images\075eef1093333ea7e549171954084b9c.jpg
..\final_dataset\test\labels\075eef1093333ea7e549171954084b9c.txt
74     ..\final_dataset\test\images\0761aca26eb706f1f004ad15842cbd03.jpg
..\final_dataset\test\labels\0761aca26eb706f1f004ad15842cbd03.txt
75     ..\final_dataset\test\images\07868d18d10b2b9eb15b935c30965436.jpg
..\final_dataset\test\labels\07868d18d10b2b9eb15b935c30965436.txt
76     ..\final_dataset\test\images\07ab2377088bd20c261291812ffe770c.jpg
..\final_dataset\test\labels\07ab2377088bd20c261291812ffe770c.txt
77     ..\final_dataset\test\images\07c22423a1fc3996fa5aef5af0afe152.jpg
..\final_dataset\test\labels\07c22423a1fc3996fa5aef5af0afe152.txt
78     ..\final_dataset\test\images\07dba76a00d1a44dbff4c9940d21978e.jpg
..\final_dataset\test\labels\07dba76a00d1a44dbff4c9940d21978e.txt
79     ..\final_dataset\test\images\07ff63ce0a662670b47afe6ed5b5af27.jpg
..\final_dataset\test\labels\07ff63ce0a662670b47afe6ed5b5af27.txt
80     ..\final_dataset\test\images\08237133378d44a215de1bce970cd0fa.jpg
..\final_dataset\test\labels\08237133378d44a215de1bce970cd0fa.txt
81     ..\final_dataset\test\images\08393207d7a27fa1f1a8ea16025a2e8c.jpg
..\final_dataset\test\labels\08393207d7a27fa1f1a8ea16025a2e8c.txt
82     ..\final_dataset\test\images\083ce87a7a2ce12bfa15a9120d73420d.jpg
..\final_dataset\test\labels\083ce87a7a2ce12bfa15a9120d73420d.txt
83     ..\final_dataset\test\images\08495f9c379ea65a152f42565a8515c6.jpg
..\final_dataset\test\labels\08495f9c379ea65a152f42565a8515c6.txt
84     ..\final_dataset\test\images\08593d91aafced55100efa2f2b043f6a.jpg
..\final_dataset\test\labels\08593d91aafced55100efa2f2b043f6a.txt
85     ..\final_dataset\test\images\085cf48b8db9946062974c5715ba9b2f.jpg
..\final_dataset\test\labels\085cf48b8db9946062974c5715ba9b2f.txt
86     ..\final_dataset\test\images\08a435e606f77f76e102fefe32dad461.jpg
..\final_dataset\test\labels\08a435e606f77f76e102fefe32dad461.txt
87     ..\final_dataset\test\images\08b11baa46e2d9185dd9ee4af5ce89fc.jpg
..\final_dataset\test\labels\08b11baa46e2d9185dd9ee4af5ce89fc.txt
88     ..\final_dataset\test\images\08d23b122205694a9a577cb8f5a8b731.jpg
..\final_dataset\test\labels\08d23b122205694a9a577cb8f5a8b731.txt
89     ..\final_dataset\test\images\08d623767686569f72a71c2ad1ded3a2.jpg
..\final_dataset\test\labels\08d623767686569f72a71c2ad1ded3a2.txt
90     ..\final_dataset\test\images\08e60e94f7b89c4af429fb973099483f.jpg
..\final_dataset\test\labels\08e60e94f7b89c4af429fb973099483f.txt
91     ..\final_dataset\test\images\08f2a7995d6fcab1326bf7dc8516a17a.jpg
..\final_dataset\test\labels\08f2a7995d6fcab1326bf7dc8516a17a.txt
92     ..\final_dataset\test\images\08f2f954d01b12fb51ee2a94050425b1.jpg
..\final_dataset\test\labels\08f2f954d01b12fb51ee2a94050425b1.txt
93     ..\final_dataset\test\images\090db97318b1ff0bd31c9335f4cde6bd.jpg
..\final_dataset\test\labels\090db97318b1ff0bd31c9335f4cde6bd.txt
94     ..\final_dataset\test\images\091511ff399fad9aa0dedab69c2fae68.jpg
..\final_dataset\test\labels\091511ff399fad9aa0dedab69c2fae68.txt
95     ..\final_dataset\test\images\091b85b2e10a25dd99291c7c395e72be.jpg
..\final_dataset\test\labels\091b85b2e10a25dd99291c7c395e72be.txt
96     ..\final_dataset\test\images\0929b096c8b294b4d223ac110f8b2ea2.jpg
..\final_dataset\test\labels\0929b096c8b294b4d223ac110f8b2ea2.txt
97     ..\final_dataset\test\images\09316ee979bbab04160d203fba27654d.jpg
..\final_dataset\test\labels\09316ee979bbab04160d203fba27654d.txt
98     ..\final_dataset\test\images\0934ea09f7b305590f6956e72e867554.jpg
..\final_dataset\test\labels\0934ea09f7b305590f6956e72e867554.txt
99     ..\final_dataset\test\images\0941945338ce153d93470639b1ef86af.jpg
..\final_dataset\test\labels\0941945338ce153d93470639b1ef86af.txt
100     ..\final_dataset\test\images\0981be739f27d5f8d718dc8face3ad16.jpg
..\final_dataset\test\labels\0981be739f27d5f8d718dc8face3ad16.txt
101     ..\final_dataset\test\images\098a711dac16c44c757e182ecbf32b45.jpg
..\final_dataset\test\labels\098a711dac16c44c757e182ecbf32b45.txt
102     ..\final_dataset\test\images\09b1d6b69ad7c35d07567f4edab0252f.jpg
..\final_dataset\test\labels\09b1d6b69ad7c35d07567f4edab0252f.txt
103     ..\final_dataset\test\images\09bbcf8086101b1b7c7bc2c3440b9c49.jpg
..\final_dataset\test\labels\09bbcf8086101b1b7c7bc2c3440b9c49.txt
104     ..\final_dataset\test\images\09cc6ad6ad6bb017fa21047238ac6da9.jpg
..\final_dataset\test\labels\09cc6ad6ad6bb017fa21047238ac6da9.txt
105     ..\final_dataset\test\images\09d29a54d8cff4be75f36628045cd692.jpg
..\final_dataset\test\labels\09d29a54d8cff4be75f36628045cd692.txt
106     ..\final_dataset\test\images\0a2a11a8658d69b6cd1fd23c5f4513bd.jpg
..\final_dataset\test\labels\0a2a11a8658d69b6cd1fd23c5f4513bd.txt
107     ..\final_dataset\test\images\0a369680dee83f1d0b5e4c3cf72f1d28.jpg
..\final_dataset\test\labels\0a369680dee83f1d0b5e4c3cf72f1d28.txt
108     ..\final_dataset\test\images\0a43582113c2f8f9a9f45fac4dc9c9e9.jpg
..\final_dataset\test\labels\0a43582113c2f8f9a9f45fac4dc9c9e9.txt
109     ..\final_dataset\test\images\0a925520d46afcc748af12455ef6df73.jpg
..\final_dataset\test\labels\0a925520d46afcc748af12455ef6df73.txt
110     ..\final_dataset\test\images\0aa2343e56637b1b9f83d7fae6f038dd.jpg
..\final_dataset\test\labels\0aa2343e56637b1b9f83d7fae6f038dd.txt
111     ..\final_dataset\test\images\0ab51f85e3b121a3692f5b47b7120088.jpg
..\final_dataset\test\labels\0ab51f85e3b121a3692f5b47b7120088.txt
112     ..\final_dataset\test\images\0aedfb73a3940401cefedb1e1f42fe8c.jpg
..\final_dataset\test\labels\0aedfb73a3940401cefedb1e1f42fe8c.txt
113     ..\final_dataset\test\images\0af3a80affb05a409c3348a3f3c4986e.jpg
..\final_dataset\test\labels\0af3a80affb05a409c3348a3f3c4986e.txt
114     ..\final_dataset\test\images\0afa8651a51d7bec65bf32d378dfa4fd.jpg
..\final_dataset\test\labels\0afa8651a51d7bec65bf32d378dfa4fd.txt
115     ..\final_dataset\test\images\0b055ebbd6dff0088d6afcfa47a9ffe9.jpg
..\final_dataset\test\labels\0b055ebbd6dff0088d6afcfa47a9ffe9.txt
116     ..\final_dataset\test\images\0b24bcf1fbf22e0b81f36378f7ca386d.jpg
..\final_dataset\test\labels\0b24bcf1fbf22e0b81f36378f7ca386d.txt
117     ..\final_dataset\test\images\0b6b5673db60dcdff9e3a663fda5cac8.jpg
..\final_dataset\test\labels\0b6b5673db60dcdff9e3a663fda5cac8.txt
118     ..\final_dataset\test\images\0b7cf85e363fe100cfe9c90ce72bbc6e.jpg
..\final_dataset\test\labels\0b7cf85e363fe100cfe9c90ce72bbc6e.txt
119     ..\final_dataset\test\images\0ba7244fc89b71d45179500a9a25e650.jpg
..\final_dataset\test\labels\0ba7244fc89b71d45179500a9a25e650.txt
120     ..\final_dataset\test\images\0bb0f54cab3693065377652f1563f2de.jpg
..\final_dataset\test\labels\0bb0f54cab3693065377652f1563f2de.txt
121     ..\final_dataset\test\images\0bec68f174b74c4d6fb32eb5794f2490.jpg
..\final_dataset\test\labels\0bec68f174b74c4d6fb32eb5794f2490.txt
122     ..\final_dataset\test\images\0bfb6405e0451ac7fb1e119ac0286f0c.jpg
..\final_dataset\test\labels\0bfb6405e0451ac7fb1e119ac0286f0c.txt
123     ..\final_dataset\test\images\0c1ebdb707a7585af9d8676db946c372.jpg
..\final_dataset\test\labels\0c1ebdb707a7585af9d8676db946c372.txt
124     ..\final_dataset\test\images\0c642835bc7fedf7989a1ad1a37227c7.jpg
..\final_dataset\test\labels\0c642835bc7fedf7989a1ad1a37227c7.txt
125     ..\final_dataset\test\images\0c6513977f4cb9678e0f7fcf4e9d7970.jpg
..\final_dataset\test\labels\0c6513977f4cb9678e0f7fcf4e9d7970.txt
126     ..\final_dataset\test\images\0cc3bfac5ca69584b706bb2e869e0e4f.jpg
..\final_dataset\test\labels\0cc3bfac5ca69584b706bb2e869e0e4f.txt
127     ..\final_dataset\test\images\0cd99a9ee135c7618006540f5b6d9b1b.jpg
..\final_dataset\test\labels\0cd99a9ee135c7618006540f5b6d9b1b.txt
128     ..\final_dataset\test\images\0ced1665ced41120d59298dc71e8bedd.jpg
..\final_dataset\test\labels\0ced1665ced41120d59298dc71e8bedd.txt
129     ..\final_dataset\test\images\0d49254795a3b9e681914b81730e1d30.jpg
..\final_dataset\test\labels\0d49254795a3b9e681914b81730e1d30.txt
130     ..\final_dataset\test\images\0d4967170de7d1780f7d152da11cd732.jpg
..\final_dataset\test\labels\0d4967170de7d1780f7d152da11cd732.txt
131     ..\final_dataset\test\images\0d4d1d4c8246d773af1ed31f1f790f5c.jpg
..\final_dataset\test\labels\0d4d1d4c8246d773af1ed31f1f790f5c.txt
132     ..\final_dataset\test\images\0d693e999750c2e4a75e9a7c359e7ec3.jpg
..\final_dataset\test\labels\0d693e999750c2e4a75e9a7c359e7ec3.txt
133     ..\final_dataset\test\images\0d9b4f7c3297e073182a9d2ef43b2bfd.jpg
..\final_dataset\test\labels\0d9b4f7c3297e073182a9d2ef43b2bfd.txt
134     ..\final_dataset\test\images\0d9c926842db11ebd6a572ea9249d531.jpg
..\final_dataset\test\labels\0d9c926842db11ebd6a572ea9249d531.txt
135     ..\final_dataset\test\images\0d9d5e1d41abb90a1b8f2997a6e66399.jpg
..\final_dataset\test\labels\0d9d5e1d41abb90a1b8f2997a6e66399.txt
136     ..\final_dataset\test\images\0da9d07f26405828067613bc74fb70a3.jpg
..\final_dataset\test\labels\0da9d07f26405828067613bc74fb70a3.txt
137     ..\final_dataset\test\images\0db5b411ea102b6af1e619b062035209.jpg
..\final_dataset\test\labels\0db5b411ea102b6af1e619b062035209.txt
138     ..\final_dataset\test\images\0dc3f3e32533d1909ec496e32a3f916c.jpg
..\final_dataset\test\labels\0dc3f3e32533d1909ec496e32a3f916c.txt
139     ..\final_dataset\test\images\0de4324225fe64cb236feca017916367.jpg
..\final_dataset\test\labels\0de4324225fe64cb236feca017916367.txt
140     ..\final_dataset\test\images\0df039260ed7ea35241dae4fb0ba8ce3.jpg
..\final_dataset\test\labels\0df039260ed7ea35241dae4fb0ba8ce3.txt
141     ..\final_dataset\test\images\0df13a9acd4b7584ab5373ea3cb58e7b.jpg
..\final_dataset\test\labels\0df13a9acd4b7584ab5373ea3cb58e7b.txt
142     ..\final_dataset\test\images\0e2f466a4feb04bd594d6e6a2350c340.jpg
..\final_dataset\test\labels\0e2f466a4feb04bd594d6e6a2350c340.txt
143     ..\final_dataset\test\images\0e330e9bf5936492ac8838547156839b.jpg
..\final_dataset\test\labels\0e330e9bf5936492ac8838547156839b.txt
144     ..\final_dataset\test\images\0e3a34450bf78053f942d73a731215e1.jpg

In [13]:
#creates csv for labels in test

with (open(path_test_img/'metadata.csv', 'w', newline='') as output_file):
    csv_writer = csv.writer(output_file)
    csv_writer.writerow(['file_name','label','x_center', 'y_center', 'width', 'height'])
    
    for file in path_test_labels.glob('*.txt'):
        with open(file,'r') as f:
            lines = f.readlines()
            file_name = file.stem+'.jpg'
            for line in lines:
                row = [file_name]
                row.extend(line.split(' '))
                row[-1]=row[-1].strip('\n')
                csv_writer.writerow(row)
                print(row)
        f.close()        
    output_file.close()

['000106393cfe2343888c584e65fd2274.jpg', 'F16', '0.2552556818181818', '0.28878281622911695', '0.5099431818181818', '0.5767700875099443']
['0039eb1ff33d29c55f943e05730bb259.jpg', 'C2', '0.4683333333333333', '0.49333333333333335', '0.6655555555555556', '0.3466666666666667']
['0041e69431bf872309d1aff628b6494f.jpg', 'E2', '0.5531665363565286', '0.6186206896551724', '0.7670054730258014', '0.46206896551724136']
['0049943dd024c06611a90feb5acebbbd.jpg', 'Mig31', '0.5930094786729858', '0.45066666666666666', '0.07582938388625593', '0.030222222222222223']
['0049943dd024c06611a90feb5acebbbd.jpg', 'F35', '0.5062203791469194', '0.7528888888888889', '0.06575829383886256', '0.02311111111111111']
['009a5b410ff34d171280c1135e15c011.jpg', 'C5', '0.479296875', '0.5604460093896714', '0.20546875', '0.15140845070422534']
['00b627cb5578bb036edb01cdcf7b56d9.jpg', 'F35', '0.6957692307692308', '0.422722029988466', '0.4576923076923077', '0.3748558246828143']
['011ced9d123e0da9c289e94a3b11165e.jpg', 'V22', '0.51375', '0.49777777777777776', '0.8841666666666667', '0.4237037037037037']
['012da930e0406f7ffe8e0f3af74fed0e.jpg', 'C130', '0.6684375', '0.8242736644798501', '0.334375', '0.1527647610121837']
['012da930e0406f7ffe8e0f3af74fed0e.jpg', 'B2', '0.4971875', '0.46438612933458295', '0.949375', '0.22586691658856609']
['0173b9cb6de97440d92705a5369857dc.jpg', 'V22', '0.35', '0.61', '0.5583333333333333', '0.335']
['01a9523f09174abae4f2b63e52a99482.jpg', 'Rafale', '0.88720703125', '0.6554128440366972', '0.1630859375', '0.11596330275229358']
['01a9523f09174abae4f2b63e52a99482.jpg', 'Rafale', '0.611572265625', '0.6521100917431193', '0.15673828125', '0.11596330275229358']
['01a9523f09174abae4f2b63e52a99482.jpg', 'Rafale', '0.648681640625', '0.7889908256880734', '0.46142578125', '0.24880733944954128']
['01a9523f09174abae4f2b63e52a99482.jpg', 'Rafale', '0.1015625', '0.6064220183486239', '0.111328125', '0.08770642201834862']
['01a9523f09174abae4f2b63e52a99482.jpg', 'Rafale', '0.2965087890625', '0.5664220183486238', '0.066162109375', '0.05100917431192661']
['01bcd847232dd6d65ed07606fd537400.jpg', 'F16', '0.50125', '0.47461273666092946', '0.52', '0.6049913941480206']
['01c2435888ca6cb8e59eaf199d85b608.jpg', 'C130', '0.29728682170542636', '0.2777777777777778', '0.5937984496124031', '0.4842377260981912']
['01fc41e0e2a068bdb46341bea333cd1c.jpg', 'F14', '0.41040462427745666', '0.42433234421364985', '0.15606936416184972', '0.05341246290801187']
['01fc41e0e2a068bdb46341bea333cd1c.jpg', 'F14', '0.7066473988439307', '0.5356083086053413', '0.24855491329479767', '0.0840751730959446']
['01fc41e0e2a068bdb46341bea333cd1c.jpg', 'F14', '0.5166184971098265', '0.8130563798219584', '0.9234104046242775', '0.2828882294757666']
['01fc41e0e2a068bdb46341bea333cd1c.jpg', 'F18', '0.5057803468208093', '0.18447082096933728', '0.861271676300578', '0.27398615232443124']
['01fcc92616f43f46c5356f82eb1e9b77.jpg', 'J10', '0.49513776337115073', '0.4594240837696335', '0.9270664505672609', '0.6989528795811518']
['0219f152494be3d3caa07264ad61887e.jpg', 'F14', '0.7467222884386174', '0.17188422917897223', '0.11164084227254668', '0.08860011813349085']
['023b32ea680c00d59c34f254b87400f6.jpg', 'F14', '0.8561622464898596', '0.0543322163714696', '0.078003120124805', '0.07132599329822882']
['023b32ea680c00d59c34f254b87400f6.jpg', 'F14', '0.871606864274571', '0.17280995691718526', '0.20249609984399375', '0.1790330301579703']
['023b32ea680c00d59c34f254b87400f6.jpg', 'F14', '0.7717628705148206', '0.5837721397797989', '0.22932917316692666', '0.12781235040689326']
['023b32ea680c00d59c34f254b87400f6.jpg', 'F14', '0.7450858034321373', '0.7915270464337003', '0.3407176287051482', '0.24174246050741982']
['023b32ea680c00d59c34f254b87400f6.jpg', 'F14', '0.13057722308892356', '0.8298228817616085', '0.231201248049922', '0.09047391096218287']
['023b32ea680c00d59c34f254b87400f6.jpg', 'F14', '0.1310452418096724', '0.4013882240306367', '0.24648985959438377', '0.1067496409765438']
['023cc897edc78f676fd1f2f347d80e83.jpg', 'F14', '0.5493723849372385', '0.3047619047619048', '0.19665271966527198', '0.33650793650793653']
['023cc897edc78f676fd1f2f347d80e83.jpg', 'F14', '0.19456066945606695', '0.6134920634920635', '0.3623430962343096', '0.48095238095238096']
['024935fca7e34a4ffd001a205eadbe58.jpg', 'Rafale', '0.6817708333333333', '0.5097580015612803', '0.08020833333333334', '0.1358313817330211']
['024935fca7e34a4ffd001a205eadbe58.jpg', 'Rafale', '0.17604166666666668', '0.6323185011709602', '0.03333333333333333', '0.09836065573770492']
['0264281592520685b7c6505d2819769f.jpg', 'P3', '0.5073839662447257', '0.07988624612202688', '0.9852320675105485', '0.0656670113753878']
['0264281592520685b7c6505d2819769f.jpg', 'P3', '0.5137130801687764', '0.2171664943123061', '0.930379746835443', '0.12409513960703206']
['0264281592520685b7c6505d2819769f.jpg', 'P3', '0.4831223628691983', '0.41933815925542917', '0.9156118143459916', '0.06204756980351603']
['0264281592520685b7c6505d2819769f.jpg', 'P3', '0.5232067510548524', '0.7083764219234746', '0.9113924050632911', '0.12306101344364012']
['0264281592520685b7c6505d2819769f.jpg', 'P3', '0.7616033755274262', '0.6119441571871769', '0.4008438818565401', '0.07704239917269907']
['0264281592520685b7c6505d2819769f.jpg', 'P3', '0.509493670886076', '0.9077042399172699', '0.8839662447257384', '0.13598759048603928']
['0266d078bb467076817b8e7c58490a46.jpg', 'V22', '0.5205263157894737', '0.5007898894154819', '0.7252631578947368', '0.9984202211690363']
['0270ff077bad1a1be7eb92a0e82cd107.jpg', 'B1', '0.4953835227272727', '0.511265164644714', '0.4580965909090909', '0.2530329289428076']
['0270ff077bad1a1be7eb92a0e82cd107.jpg', 'B1', '0.6441761363636364', '0.4584055459272097', '0.06392045454545454', '0.03292894280762565']
['02734fcb986f51711325d049ec55d14e.jpg', 'F4', '0.5329166666666667', '0.63875', '0.8641666666666666', '0.535']
['02734fcb986f51711325d049ec55d14e.jpg', 'F15', '0.8366666666666667', '0.346875', '0.065', '0.03625']
['02785b7f8e63e54cc31aa80accc6e590.jpg', 'V22', '0.2708333333333333', '0.078125', '0.16666666666666666', '0.04375']
['02785b7f8e63e54cc31aa80accc6e590.jpg', 'V22', '0.5152777777777777', '0.13046875', '0.1361111111111111', '0.03125']
['02785b7f8e63e54cc31aa80accc6e590.jpg', 'V22', '0.12777777777777777', '0.098828125', '0.17777777777777778', '0.03828125']
['02785b7f8e63e54cc31aa80accc6e590.jpg', 'V22', '0.9756944444444444', '0.45859375', '0.04027777777777778', '0.009375']
['02785b7f8e63e54cc31aa80accc6e590.jpg', 'V22', '0.8611111111111112', '0.451953125', '0.044444444444444446', '0.01015625']
['02785b7f8e63e54cc31aa80accc6e590.jpg', 'V22', '0.9034722222222222', '0.44609375', '0.05138888888888889', '0.0109375']
['0285d1b04f2c55e90f78a072446e4fd3.jpg', 'V22', '0.5704166666666667', '0.5118518518518519', '0.0225', '0.01925925925925926']
['029951993b9278dbc2f7f88755d79d7b.jpg', 'SR71', '0.53875', '0.5426716141001855', '0.7225', '0.274582560296846']
['02a0a447a3bcc9cf947e149f881eaf9a.jpg', 'C2', '0.4980392156862745', '0.4514705882352941', '0.1450980392156863', '0.07352941176470588']
['02c66bc41180665edf37ff4caf7bc1e4.jpg', 'Su24', '0.6232394366197183', '0.8157380254154448', '0.5241448692152918', '0.18670576735092864']
['02c66bc41180665edf37ff4caf7bc1e4.jpg', 'Su24', '0.3777665995975855', '0.19403714565004887', '0.5462776659959758', '0.19648093841642228']
['02df5f88c2dd366113aa6abc906e8b83.jpg', 'US2', '0.650390625', '0.5088757396449705', '0.658203125', '0.39644970414201186']
['0366e9b9b25ca38d17fda3eb0032b009.jpg', 'F22', '0.30809128630705396', '0.2598547717842324', '0.23340248962655602', '0.33713692946058094']
['0366e9b9b25ca38d17fda3eb0032b009.jpg', 'F15', '0.6854253112033195', '0.5063969571230982', '0.18931535269709543', '0.18983402489626555']
['0397c5392ba5190f798fe04de92d52dc.jpg', 'C5', '0.7119170984455958', '0.44991364421416236', '0.5761658031088083', '0.696027633851468']
['03b84839ca5a7fa48209f714241b6ef5.jpg', 'F35', '0.8245', '0.6754122938530734', '0.149', '0.08845577211394302']
['03b84839ca5a7fa48209f714241b6ef5.jpg', 'F35', '0.15', '0.6664167916041979', '0.16', '0.0944527736131934']
['03bee5224965f2d87bd397b7ddd50875.jpg', 'SR71', '0.5068681318681318', '0.42857142857142855', '0.945054945054945', '0.589010989010989']
['03cb9dd1710ef0eb165be3ff44b8ef70.jpg', 'F15', '0.43385416666666665', '0.5075901328273245', '0.11666666666666667', '0.174573055028463']
['03cb9dd1710ef0eb165be3ff44b8ef70.jpg', 'F15', '0.6018229166666667', '0.43026565464895633', '0.1046875', '0.14895635673624288']
['03cb9dd1710ef0eb165be3ff44b8ef70.jpg', 'Mirage2000', '0.8380208333333333', '0.3178368121442125', '0.058333333333333334', '0.0872865275142315']
['03cb9dd1710ef0eb165be3ff44b8ef70.jpg', 'Mirage2000', '0.13958333333333334', '0.2642314990512334', '0.06041666666666667', '0.08633776091081594']
['03cb9dd1710ef0eb165be3ff44b8ef70.jpg', 'Rafale', '0.23619791666666667', '0.3742884250474383', '0.08177083333333333', '0.11669829222011385']
['03cb9dd1710ef0eb165be3ff44b8ef70.jpg', 'Rafale', '0.72421875', '0.3600569259962049', '0.07552083333333333', '0.10531309297912714']
['03e7dd6896f2169a2a94344b0b2fc254.jpg', 'Mig31', '0.5002821670428894', '0.4995766299745978', '0.9994356659142212', '0.5300592718035563']
['03f7bc02b925509cb507d2f4b9725e4e.jpg', 'J20', '0.3076171875', '0.5458860759493671', '0.134765625', '0.08544303797468354']
['03f7bc02b925509cb507d2f4b9725e4e.jpg', 'J20', '0.712890625', '0.3275316455696203', '0.1328125', '0.08227848101265822']
['04170bd2af2b63d2a7df5bc4e6be7a51.jpg', 'US2', '0.55390625', '0.5010416666666667', '0.8921875', '0.9979166666666667']
['043ddd1cc154aefeeb4b57c9b2e56982.jpg', 'C130', '0.5001267427122941', '0.3365019011406844', '0.9997465145754119', '0.6722433460076046']
['044425a07b59ca9b0f128f4f54eacc9a.jpg', 'B1', '0.207275390625', '0.44143484626647145', '0.32958984375', '0.12445095168374817']
['044425a07b59ca9b0f128f4f54eacc9a.jpg', 'F16', '0.297607421875', '0.47108345534407026', '0.19482421875', '0.10029282576866765']
['044425a07b59ca9b0f128f4f54eacc9a.jpg', 'F16', '0.270263671875', '0.5018301610541728', '0.31396484375', '0.17935578330893118']
['044425a07b59ca9b0f128f4f54eacc9a.jpg', 'F35', '0.543212890625', '0.4718155197657394', '0.05322265625', '0.02562225475841874']
['044425a07b59ca9b0f128f4f54eacc9a.jpg', 'F16', '0.4306640625', '0.5095168374816984', '0.517578125', '0.25036603221083453']
['044425a07b59ca9b0f128f4f54eacc9a.jpg', 'B1', '0.42822265625', '0.465592972181552', '0.6279296875', '0.19326500732064422']
['044425a07b59ca9b0f128f4f54eacc9a.jpg', 'F35', '0.959716796875', '0.4535139092240117', '0.08056640625', '0.04465592972181552']
['044425a07b59ca9b0f128f4f54eacc9a.jpg', 'F16', '0.56982421875', '0.6138360175695461', '0.837890625', '0.47218155197657397']
['0452c8bd37594601465039eb424bf294.jpg', 'C2', '0.5198529411764706', '0.4693627450980392', '0.6455882352941177', '0.33578431372549017']
['045bf96a1debb70f997e817e2fd46a1c.jpg', 'MQ9', '0.5225830078125', '0.3614678899082569', '0.954833984375', '0.6774311926605504']
['045bf96a1debb70f997e817e2fd46a1c.jpg', 'MQ9', '0.57275390625', '0.5772477064220184', '0.33251953125', '0.1218348623853211']
['0464dd1a30aaf3fcb58646d85fb3c044.jpg', 'F15', '0.6676025390625', '0.6480190755685987', '0.184326171875', '0.1243580337490829']
['0464dd1a30aaf3fcb58646d85fb3c044.jpg', 'F15', '0.330810546875', '0.6406823184152605', '0.25146484375', '0.17131327953044753']
['0466439003f7b9214a3a15bde1831e3b.jpg', 'Su57', '0.5088272383354351', '0.48616600790513836', '0.9016393442622951', '0.8959156785243741']
['047cc850b8d18427ce24e77b766d14db.jpg', 'F16', '0.49625', '0.513125', '0.9916666666666667', '0.40208333333333335']
['048831fe15e2938828b9316fa978cbc3.jpg', 'US2', '0.5579166666666666', '0.486875', '0.36583333333333334', '0.15625']
['04a3d479d3aaf701476a705526bde6ee.jpg', 'RQ4', '0.4937744140625', '0.46338337605272795', '0.546142578125', '0.3203954595386305']
['04a73f4f1bde123f42e5a9240be9eb0e.jpg', 'F15', '0.6131591796875', '0.09230769230769231', '0.209716796875', '0.13406593406593406']
['04ae480f61539d26f8b45fdb4714226d.jpg', 'F16', '0.761474609375', '0.81494140625', '0.46923828125', '0.1376953125']
['04ae480f61539d26f8b45fdb4714226d.jpg', 'F16', '0.250732421875', '0.83349609375', '0.49462890625', '0.2646484375']
['04cefb66f077ecec12f617e751697d3f.jpg', 'F35', '0.621141975308642', '0.8535879629629629', '0.03446502057613169', '0.011959876543209876']
['04cefb66f077ecec12f617e751697d3f.jpg', 'F16', '0.42039609053497945', '0.42804783950617287', '0.030606995884773662', '0.019675925925925927']
['04f96296dc4e450031042387d3eddf6e.jpg', 'JAS39', '0.50634765625', '0.43924581005586594', '0.8994140625', '0.4092178770949721']
['04fe842dda2e9fd25e75cef5d12b38a0.jpg', 'F4', '0.5047169811320755', '0.5018832391713748', '0.9905660377358491', '0.504708097928437']
['050a9b7530e2e02211ee387f0e528dec.jpg', 'F4', '0.5004166666666666', '0.5288888888888889', '0.9525', '0.5303703703703704']
['050b54dee22d97329b7355d9ecff4f47.jpg', 'F4', '0.5756944444444444', '0.759375', '0.09861111111111111', '0.06875']
['050b54dee22d97329b7355d9ecff4f47.jpg', 'Tu95', '0.35347222222222224', '0.5375', '0.3958333333333333', '0.175']
['0560e20e68dac2114517822a25ee31f4.jpg', 'E2', '0.5380859375', '0.5666178623718887', '0.767578125', '0.4260614934114202']
['057e708755395a051d98fa7398c0cac3.jpg', 'F35', '0.6500651041666666', '0.489501953125', '0.10221354166666667', '0.04443359375']
['058476b6a76ef809ac7c381f52666322.jpg', 'C17', '0.25833333333333336', '0.437413073713491', '0.5055555555555555', '0.2906815020862309']
['058c36a1f3c52872ae56cbf9efba3cd7.jpg', 'Be200', '0.35375494071146246', '0.179813401187447', '0.09655561829474874', '0.06276505513146735']
['058dee5bdcf0c13c2ac1a334f59ecce7.jpg', 'F18', '0.40380761523046094', '0.16020671834625322', '0.45090180360721444', '0.2739018087855297']
['058dee5bdcf0c13c2ac1a334f59ecce7.jpg', 'F18', '0.7655310621242485', '0.3733850129198966', '0.46893787575150303', '0.16279069767441862']
['058dee5bdcf0c13c2ac1a334f59ecce7.jpg', 'F18', '0.47995991983967934', '0.6136950904392765', '0.4468937875751503', '0.14728682170542637']
['058dee5bdcf0c13c2ac1a334f59ecce7.jpg', 'F18', '0.3166332665330661', '0.7002583979328165', '0.4248496993987976', '0.1343669250645995']
['059338d7fb2c2ce8cdb52d0e2fc6f002.jpg', 'F16', '0.5040322580645161', '0.5990691489361702', '0.803763440860215', '0.4853723404255319']
['059338d7fb2c2ce8cdb52d0e2fc6f002.jpg', 'F14', '0.41263440860215056', '0.28058510638297873', '0.4220430107526882', '0.2074468085106383']
['059843e8192d9e4e990da370775e1b53.jpg', 'F18', '0.2465625', '0.36833333333333335', '0.226875', '0.2922222222222222']
['0599a768519c3fcf30d0dad2545fe7c7.jpg', 'AV8B', '0.6920415224913494', '0.44096509240246407', '0.28143021914648214', '0.16324435318275154']
['0599a768519c3fcf30d0dad2545fe7c7.jpg', 'AV8B', '0.7119377162629758', '0.6827515400410678', '0.39388696655132643', '0.2464065708418891']
['05a3597048d08814796898b453f571b4.jpg', 'C130', '0.7735294117647059', '0.072265625', '0.17647058823529413', '0.0546875']
['05ef1b83fab31eb6a2547c1b5c901873.jpg', 'A400M', '0.5506666666666666', '0.5367298578199052', '0.6226666666666667', '0.4786729857819905']
['0619bf8396a765a73f7a2b8f7d04acae.jpg', 'F15', '0.5616666666666666', '0.25406758448060074', '0.09333333333333334', '0.08010012515644556']
['061c66250967a10ca840c00d844839cc.jpg', 'AV8B', '0.5848765432098766', '0.6485339506172839', '0.2916666666666667', '0.24382716049382716']
['061c66250967a10ca840c00d844839cc.jpg', 'AV8B', '0.3881172839506173', '0.3088348765432099', '0.2962962962962963', '0.251929012345679']
['0627eb82806e0e3cb3bd229a1572b69b.jpg', 'EF2000', '0.890869140625', '0.4826388888888889', '0.17919921875', '0.1597222222222222']
['0627eb82806e0e3cb3bd229a1572b69b.jpg', 'EF2000', '0.0986328125', '0.61328125', '0.16796875', '0.1449652777777778']
['0627eb82806e0e3cb3bd229a1572b69b.jpg', 'P3', '0.43115234375', '0.3454861111111111', '0.474609375', '0.2326388888888889']
['06343ae4bc2051dc5993b723a30215a5.jpg', 'C2', '0.42783505154639173', '0.5055187637969095', '0.5022091310751104', '0.26490066225165565']
['065277d6aed4a22439c9926f7df8b097.jpg', 'J20', '0.30666666666666664', '0.4625', '0.21666666666666667', '0.16666666666666666']
['065277d6aed4a22439c9926f7df8b097.jpg', 'J20', '0.71375', '0.3423611111111111', '0.2225', '0.18194444444444444']
['0677f183db212e98c1503f73f32cdb33.jpg', 'F18', '0.4453125', '0.3824074074074074', '0.5791666666666667', '0.45925925925925926']
['06b9198f251d64f43dc7cee13fc91332.jpg', 'F15', '0.5403125', '0.41799437675726336', '0.213125', '0.08059981255857544']
['06bf5da72d927d021d784e8c37cece4c.jpg', 'Su24', '0.3197124479757851', '0.5479876160990712', '0.12258796821793416', '0.4743034055727554']
['06bf5da72d927d021d784e8c37cece4c.jpg', 'Su24', '0.6394248959515701', '0.556656346749226', '0.12258796821793416', '0.47306501547987617']
['06bf5da72d927d021d784e8c37cece4c.jpg', 'Su24', '0.08702232311766932', '0.544891640866873', '0.12485811577752554', '0.4804953560371517']
['06bf5da72d927d021d784e8c37cece4c.jpg', 'Su24', '0.8912220961029134', '0.5523219814241486', '0.12296632614453273', '0.4804953560371517']
['06c47f77e389d8461799b219559b2c61.jpg', 'J20', '0.4859375', '0.5070339976553341', '0.6671875', '0.5896834701055099']
['07036a2bab3c2b6c594df2ff11933fe5.jpg', 'F18', '0.090087890625', '0.6139322916666666', '0.1240234375', '0.0837673611111111']
['07036a2bab3c2b6c594df2ff11933fe5.jpg', 'F35', '0.2255859375', '0.6232638888888888', '0.09716796875', '0.07899305555555555']
['07036a2bab3c2b6c594df2ff11933fe5.jpg', 'F117', '0.3634033203125', '0.6297743055555556', '0.115478515625', '0.07899305555555555']
['07036a2bab3c2b6c594df2ff11933fe5.jpg', 'F22', '0.5101318359375', '0.6243489583333334', '0.128662109375', '0.10026041666666667']
['07036a2bab3c2b6c594df2ff11933fe5.jpg', 'F117', '0.6427001953125', '0.6282552083333334', '0.113525390625', '0.07855902777777778']
['07036a2bab3c2b6c594df2ff11933fe5.jpg', 'F15', '0.7843017578125', '0.6111111111111112', '0.122314453125', '0.0998263888888889']
['07036a2bab3c2b6c594df2ff11933fe5.jpg', 'B1', '0.5064697265625', '0.5651041666666666', '0.253173828125', '0.109375']
['07036a2bab3c2b6c594df2ff11933fe5.jpg', 'F15', '0.4732666015625', '0.3917100694444444', '0.024169921875', '0.028211805555555556']
['07036a2bab3c2b6c594df2ff11933fe5.jpg', 'F16', '0.9229736328125', '0.6111111111111112', '0.116455078125', '0.08680555555555555']
['075eef1093333ea7e549171954084b9c.jpg', 'B2', '0.75625', '0.47921390778533635', '0.228125', '0.10128495842781557']
['0761aca26eb706f1f004ad15842cbd03.jpg', 'Vulcan', '0.6965620328849028', '0.3803986710963455', '0.4693572496263079', '0.29900332225913623']
['0761aca26eb706f1f004ad15842cbd03.jpg', 'Vulcan', '0.5014947683109118', '0.3073089700996678', '0.9566517189835575', '0.47840531561461797']
['07868d18d10b2b9eb15b935c30965436.jpg', 'A10', '0.40545454545454546', '0.5518181818181818', '0.6363636363636364', '0.34363636363636363']
['07ab2377088bd20c261291812ffe770c.jpg', 'JAS39', '0.5270833333333333', '0.4786931818181818', '0.6979166666666666', '0.5085227272727273']
['07c22423a1fc3996fa5aef5af0afe152.jpg', 'Be200', '0.5211111111111111', '0.6193656093489148', '0.5444444444444444', '0.24040066777963273']
['07dba76a00d1a44dbff4c9940d21978e.jpg', 'B2', '0.35130208333333335', '0.5187353629976581', '0.7015625', '0.7548790007806401']
['07ff63ce0a662670b47afe6ed5b5af27.jpg', 'EF2000', '0.48723293381969773', '0.411328125', '0.7701928087545596', '0.71015625']
['08237133378d44a215de1bce970cd0fa.jpg', 'C2', '0.5072222222222222', '0.2826086956521739', '0.12777777777777777', '0.07114624505928854']
['08393207d7a27fa1f1a8ea16025a2e8c.jpg', 'Be200', '0.52525', '0.509', '0.9495', '0.37133333333333335']
['083ce87a7a2ce12bfa15a9120d73420d.jpg', 'MQ9', '0.4995833333333333', '0.5476190476190477', '0.43583333333333335', '0.19047619047619047']
['08495f9c379ea65a152f42565a8515c6.jpg', 'A10', '0.32611624326404925', '0.6340080971659919', '0.08564280215550424', '0.06153846153846154']

In [14]:
# convert labels from csv to json
df = pd.read_csv(path_test_img/'metadata.csv')
df.to_json(path_test_img/'metadata.json', orient='records')

In [16]:
df

,file_name,label,x_center,y_center,width,height
0,000106393cfe2343888c584e65fd2274.jpg,F16,0.255256,0.288783,0.509943,0.576770
1,0039eb1ff33d29c55f943e05730bb259.jpg,C2,0.468333,0.493333,0.665556,0.346667
2,0041e69431bf872309d1aff628b6494f.jpg,E2,0.553167,0.618621,0.767005,0.462069
3,0049943dd024c06611a90feb5acebbbd.jpg,Mig31,0.593009,0.450667,0.075829,0.030222
4,0049943dd024c06611a90feb5acebbbd.jpg,F35,0.506220,0.752889,0.065758,0.023111
...,...,...,...,...,...,...
323,126a0390052f8ffe741733de6763a740.jpg,F35,0.308333,0.599184,0.125556,0.063976
324,126a0390052f8ffe741733de6763a740.jpg,F35,0.184444,0.603693,0.120000,0.065264
325,1272cdf4e852b5e89adbbb3c65cd68ad.jpg,F117,0.698452,0.291040,0.118989,0.070956
326,1272cdf4e852b5e89adbbb3c65cd68ad.jpg,F117,0.840668,0.359892,0.113284,0.064342
327,1272cdf4e852b5e89adbbb3c65cd68ad.jpg,F117,0.490220,0.483464,0.978810,0.315093

# Curating Train dataset

In [6]:
from pathlib import Path
import shutil
from tqdm.notebook import tqdm
import csv
import numpy as np
import pandas as pd
import json

In [5]:
path_full_img = Path('../final_dataset/train/images')
path_full_labels = Path('../final_dataset/train/labels')
path_train_img = Path('../lite_dataset/train/images')
path_train_labels = Path('../lite_dataset/train/labels')

In [4]:
if not path_train_img.exists() and not path_train_labels.exists():
    try:
        path_train_img.mkdir(parents=True)
        path_train_labels.mkdir(parents=True)
        print('Path train dataset created!')
    except Exception as e:
        print('Path train dataset creation failed!' , e)

Path test dataset created!

In [8]:
# copy img and labels file to test folder
# where TEST_NUM is number of files
TRAIN_NUM = 1000
itr = 1
for file in tqdm(path_full_img.glob('*.jpg')):
    # print(itr,'   ',file)
    label_path= Path(path_full_labels,file.stem+'.txt')
    shutil.copy(file, path_train_img)
    shutil.copy(label_path, path_train_labels)
    # print(label_path)
    
    
    if itr >= TRAIN_NUM:
        break
    itr += 1

0it [00:00, ?it/s]

In [9]:
#creates metadata for labels in train

with (open(path_train_img/'metadata.csv', 'w', newline='') as output_file):
    csv_writer = csv.writer(output_file)
    csv_writer.writerow(['file_name','label','x_center', 'y_center', 'width', 'height'])
    
    for file in tqdm(path_train_labels.glob('*.txt')):
        with open(file,'r') as f:
            lines = f.readlines()
            file_name = file.stem+'.jpg'
            for line in lines:
                row = [file_name]
                row.extend(line.split(' '))
                row[-1]=row[-1].strip('\n')
                csv_writer.writerow(row)
                print(row)
        f.close()        
    output_file.close()

0it [00:00, ?it/s]

['00032844ab679240fc03ecd27d29a6aa.jpg', 'F18', '0.516725352112676', '0.3884976525821596', '0.9665492957746479', '0.7582159624413145']
['0003f56298fa8999168d7988a2e9549d.jpg', 'F22', '0.46502718734552645', '0.39451242120875046', '0.8247652001977261', '0.41453466814979606']
['0003f56298fa8999168d7988a2e9549d.jpg', 'F22', '0.5568462679189323', '0.44123099740452354', '0.8863074641621355', '0.4649610678531702']
['000aa01b25574f28b654718db0700f72.jpg', 'F35', '0.69580078125', '0.2490842490842491', '0.5595703125', '0.23882783882783884']
['000aa01b25574f28b654718db0700f72.jpg', 'JAS39', '0.17529296875', '0.6087912087912087', '0.185546875', '0.09084249084249084']
['000aa01b25574f28b654718db0700f72.jpg', 'JAS39', '0.137939453125', '0.7021978021978021', '0.15380859375', '0.073992673992674']
['000aa01b25574f28b654718db0700f72.jpg', 'B52', '0.382080078125', '0.7611721611721611', '0.49365234375', '0.2021978021978022']
['000e7662268a1071827c5a8663e773f9.jpg', 'US2', '0.7175', '0.4304906542056075', '0.565', '0.3002336448598131']
['000ec980b5b17156a55093b4bd6004ab.jpg', 'Be200', '0.4795', '0.2967332123411978', '0.343', '0.13611615245009073']
['0036c2784a5b8b2a4a1a4bd9109eb2f7.jpg', 'EF2000', '0.503173828125', '0.5929969879518072', '0.29736328125', '0.2914156626506024']
['0048b6531d2792ef6f5b7235b357a348.jpg', 'Rafale', '0.3848958333333333', '0.2608333333333333', '0.06145833333333333', '0.016666666666666666']
['0051a45cc908d93660f686df975c2bbc.jpg', 'F35', '0.49557522123893805', '0.47040905134899913', '0.041719342604298354', '0.02175805047867711']
['0052d815facb55cf9f6f639a1647a0a5.jpg', 'B52', '0.5194444444444445', '0.3283333333333333', '0.9611111111111111', '0.56']
['0052ebf62f5f24c027a08b99ab00c9b9.jpg', 'F18', '0.73125', '0.6622222222222223', '0.0925', '0.04666666666666667']
['0052ebf62f5f24c027a08b99ab00c9b9.jpg', 'F18', '0.46625', '0.5161111111111111', '0.33916666666666667', '0.24555555555555555']
['0055583f8723e234fb5ce74f3df59cf1.jpg', 'Su25', '0.49453125', '0.49137931034482757', '0.7484375', '0.4708222811671088']
['005a2bac1b0045cd972c75110c0f378b.jpg', 'XB70', '0.5005208333333333', '0.6694444444444444', '0.9989583333333333', '0.5472222222222223']
['005e486c03142ce64736bba86b347b96.jpg', 'Be200', '0.415', '0.4525', '0.12333333333333334', '0.0675']
['0067df5849d8cfb479303936b3798aa5.jpg', 'F15', '0.916', '0.764747191011236', '0.076', '0.09129213483146068']
['0067df5849d8cfb479303936b3798aa5.jpg', 'F15', '0.9065', '0.5547752808988764', '0.077', '0.09269662921348315']
['0067df5849d8cfb479303936b3798aa5.jpg', 'F15', '0.6335', '0.5372191011235955', '0.077', '0.09410112359550561']
['0067df5849d8cfb479303936b3798aa5.jpg', 'F15', '0.073', '0.3848314606741573', '0.078', '0.0898876404494382']
['0067df5849d8cfb479303936b3798aa5.jpg', 'KC135', '0.8035', '0.3188202247191011', '0.165', '0.17696629213483145']
['006e132e1de4098544e937d56a4cf3d3.jpg', 'C2', '0.4727777777777778', '0.48007246376811596', '0.33', '0.12439613526570048']
['0079ecb92d4a99dc405dae5bde86d8a9.jpg', 'F15', '0.5258333333333334', '0.48873591989987486', '0.6183333333333333', '0.5694618272841051']
['007eb1fc3d58c86131989784a81e6615.jpg', 'E2', '0.23964968152866242', '0.185625', '0.23089171974522293', '0.13125']
['007eb1fc3d58c86131989784a81e6615.jpg', 'E2', '0.7929936305732485', '0.105', '0.23248407643312102', '0.1325']
['007eb1fc3d58c86131989784a81e6615.jpg', 'E2', '0.5151273885350318', '0.31375', '0.2213375796178344', '0.125']
['007eb1fc3d58c86131989784a81e6615.jpg', 'E2', '0.30971337579617836', '0.5225', '0.21178343949044587', '0.1175']
['007eb1fc3d58c86131989784a81e6615.jpg', 'E2', '0.7484076433121019', '0.486875', '0.21656050955414013', '0.12125']
['007eb1fc3d58c86131989784a81e6615.jpg', 'E2', '0.5318471337579618', '0.590625', '0.2070063694267516', '0.11375']
['007eb1fc3d58c86131989784a81e6615.jpg', 'E2', '0.3463375796178344', '0.813125', '0.1926751592356688', '0.10375']
['007eb1fc3d58c86131989784a81e6615.jpg', 'E2', '0.6624203821656051', '0.833125', '0.1942675159235669', '0.10375']
['007eb1fc3d58c86131989784a81e6615.jpg', 'E2', '0.5199044585987261', '0.91', '0.18949044585987262', '0.1025']
['0081dca65c2991b4c145de6af9845946.jpg', 'B2', '0.501', '0.7023988005997002', '0.902', '0.15142428785607195']
['008f4dc1928d36913ad0ae7d93c12a58.jpg', 'F35', '0.5778775079197466', '0.28127474267616787', '0.12090813093980993', '0.05819477434679335']
['008f4dc1928d36913ad0ae7d93c12a58.jpg', 'F35', '0.3845036958817318', '0.6672604908946952', '0.058870116156283', '0.026524148851939825']
['008fb1ddb011b63cc0b9c6107e79589f.jpg', 'US2', '0.43017578125', '0.7053941908713693', '0.4716796875', '0.4426002766251729']
['008fb1ddb011b63cc0b9c6107e79589f.jpg', 'US2', '0.59228515625', '0.34716459197787', '0.5478515625', '0.5560165975103735']
['00935c77afba93917a253d8d47dba0f5.jpg', 'Tu160', '0.5003125', '0.5768509840674789', '0.999375', '0.5538894095595126']
['00a146155690879cedf0b20325b0ba18.jpg', 'F15', '0.42568181818181816', '0.555625', '0.3459090909090909', '0.16125']
['00a174c977e5a4c112422ddbec8d9266.jpg', 'E2', '0.4681669776119403', '0.4487359550561798', '0.06459888059701492', '0.16292134831460675']
['00afb4420bdce881ad216867c713c800.jpg', 'Mig31', '0.58375', '0.47875', '0.6691666666666667', '0.465']
['00b2add164cb42440a52064e390ea3d2.jpg', 'B1', '0.474609375', '0.4294117647058823', '0.44609375', '0.5952941176470589']
['00b71e10fbe9e5bc833fea089cb512f0.jpg', 'F22', '0.5001220703125', '0.5001834862385321', '0.999755859375', '0.9996330275229358']
['00c09f406d31a0cd9402862fbd26d930.jpg', 'A10', '0.5088888888888888', '0.3441666666666667', '0.9822222222222222', '0.5883333333333334']
['00c0df556f07c96cdb0db68a1e56046c.jpg', 'B2', '0.248291015625', '0.5017361111111112', '0.09423828125', '0.015625']
['00c0df556f07c96cdb0db68a1e56046c.jpg', 'B2', '0.719970703125', '0.5199652777777778', '0.10791015625', '0.017361111111111112']
['00c469711cece905455462094a77cc4f.jpg', 'Tu160', '0.496', '0.47553017944535075', '0.99', '0.48450244698205547']
['00c469711cece905455462094a77cc4f.jpg', 'Tu160', '0.5125', '0.8450244698205547', '0.975', '0.3099510603588907']
['00c54e200e0d868faac8c55bfca70dbe.jpg', 'V22', '0.675', '0.5370833333333334', '0.27166666666666667', '0.20583333333333334']
['00cca7071121992f472ed2f15667d789.jpg', 'US2', '0.5369791666666667', '0.5740740740740741', '0.20208333333333334', '0.10740740740740741']
['00d4b7ea93ca1417393007c61c519f88.jpg', 'A10', '0.5029166666666667', '0.47185185185185186', '0.0725', '0.03111111111111111']
['00db76f676528477c66c93c7d24d7524.jpg', 'F117', '0.56875', '0.47607934655775963', '0.8625', '0.338389731621937']
['00dfd9dc1a4fe3d0a32f01cee1e3928c.jpg', 'C130', '0.6692985372340425', '0.22983067729083664', '0.3768284574468085', '0.16185258964143426']
['00ea3b9658576d41ec570bd558e81fe4.jpg', 'E7', '0.58', '0.36794019933554817', '0.608', '0.38372093023255816']
['00ea3b9658576d41ec570bd558e81fe4.jpg', 'F15', '0.416', '0.7998338870431894', '0.14', '0.08803986710963455']
['00ea3b9658576d41ec570bd558e81fe4.jpg', 'F15', '0.569', '0.8023255813953488', '0.142', '0.08970099667774087']
['00ebecac178be3c3890a067d6a28234e.jpg', 'C5', '0.49322916666666666', '0.4140625', '0.865625', '0.4125']
['00ee2f5b81e8ff2f65cfa959cf30ef02.jpg', 'XB70', '0.5010416666666667', '0.5069444444444444', '0.9979166666666667', '0.8361111111111111']
['00f4279089ddc0d40e1470894f827f2e.jpg', 'C5', '0.484619140625', '0.3761904761904762', '0.11474609375', '0.16923076923076924']
['00fb573c1614ee17103ae94d74fefddb.jpg', 'EF2000', '0.494140625', '0.33050293925538865', '0.943359375', '0.5329849771391247']
['01083dc947495bced28253b764a56460.jpg', 'F35', '0.32958984375', '0.4887152777777778', '0.5029296875', '0.4149305555555556']
['010b83d85e8bdbea1edac418d3b1da48.jpg', 'F18', '0.42230769230769233', '0.31326949384404923', '0.2523076923076923', '0.24350205198358413']
['010b83d85e8bdbea1edac418d3b1da48.jpg', 'F18', '0.5346153846153846', '0.46580027359781123', '0.19846153846153847', '0.23666210670314639']
['010b83d85e8bdbea1edac418d3b1da48.jpg', 'F18', '0.41615384615384615', '0.5779753761969905', '0.25384615384615383', '0.22845417236662108']
['010b83d85e8bdbea1edac418d3b1da48.jpg', 'F18', '0.32653846153846156', '0.4124487004103967', '0.2530769230769231', '0.2421340629274966']
['01169f9ba735dfcb46dab62bc5649de9.jpg', 'A10', '0.6539306640625', '0.11834862385321102', '0.048583984375', '0.0781651376146789']
['012c84db283e21907b9ccddfaec7e1ff.jpg', 'F18', '0.47369791666666666', '0.475390625', '0.6505208333333333', '0.72109375']
['0133451fe0ca714bbaedc4db40a01a7e.jpg', 'B1', '0.340418977202711', '0.6412037037037037', '0.33826247689463956', '0.14166666666666666']
['0133451fe0ca714bbaedc4db40a01a7e.jpg', 'F15', '0.6343191620455946', '0.29398148148148145', '0.12384473197781885', '0.06388888888888888']
['0133451fe0ca714bbaedc4db40a01a7e.jpg', 'F15', '0.7664818237831177', '0.20324074074074075', '0.1170671595810228', '0.05462962962962963']
['014240b10dffa805240c72655e357866.jpg', 'U2', '0.4881552419354839', '0.519489247311828', '0.09526209677419355', '0.03763440860215054']
['014313402292d8dbc688f9f1c50fa0ad.jpg', 'AG600', '0.500390625', '0.5140679953106683', '0.89609375', '0.3481828839390387']
['0152de18ba102f814ea28f5719f866dc.jpg', 'RQ4', '0.8877604166666667', '0.3768518518518518', '0.08072916666666667', '0.14629629629629629']
['0152de18ba102f814ea28f5719f866dc.jpg', 'RQ4', '0.26510416666666664', '0.2902777777777778', '0.1125', '0.07314814814814814']
['0152de18ba102f814ea28f5719f866dc.jpg', 'RQ4', '0.12890625', '0.29444444444444445', '0.11197916666666667', '0.07407407407407407']
['0152de18ba102f814ea28f5719f866dc.jpg', 'RQ4', '0.12994791666666666', '0.649074074074074', '0.11197916666666667', '0.07222222222222222']
['0152de18ba102f814ea28f5719f866dc.jpg', 'RQ4', '0.26875', '0.6472222222222223', '0.1125', '0.07222222222222222']
['0152de18ba102f814ea28f5719f866dc.jpg', 'U2', '0.45390625', '0.5476851851851852', '0.0890625', '0.09722222222222222']
['0152de18ba102f814ea28f5719f866dc.jpg', 'U2', '0.5796875', '0.5444444444444444', '0.08958333333333333', '0.09814814814814815']
['0152de18ba102f814ea28f5719f866dc.jpg', 'U2', '0.7046875', '0.5439814814814815', '0.08958333333333333', '0.09722222222222222']
['01539e41503813d687505821b66913de.jpg', 'B2', '0.5003846153846154', '0.5673963133640553', '0.9992307692307693', '0.4274193548387097']
['015b76d5b1b791ae276d79e6ce20cf91.jpg', 'C5', '0.42864583333333334', '0.34921875', '0.815625', '0.20625']
['01663dbe73c573696bc11ef6a9127e32.jpg', 'SR71', '0.48657407407407405', '0.5008710801393729', '0.8379629629629629', '0.9982578397212544']
['016fa8924fc440011da60cf62d87adf4.jpg', 'J10', '0.31675', '0.46886721680420107', '0.2715', '0.12303075768942236']
['016fa8924fc440011da60cf62d87adf4.jpg', 'J10', '0.59575', '0.5933983495873969', '0.1915', '0.0900225056264066']
['01724da104b0b0ab9f9b74cb4afcf293.jpg', 'F22', '0.115234375', '0.3042659974905897', '0.22109375', '0.14178168130489335']
['01724da104b0b0ab9f9b74cb4afcf293.jpg', 'F22', '0.806640625', '0.29234629861982436', '0.35390625', '0.17565872020075282']
['01731aca78a6a1b8a90217714b0ba98d.jpg', 'RQ4', '0.5004166666666666', '0.2455470737913486', '0.9991666666666666', '0.48854961832061067']
['0173a2a50e5365c920224ed4de9bfad5.jpg', 'RQ4', '0.526875', '0.544375', '0.48291666666666666', '0.1125']
['01742519344097097dd43a29597b885d.jpg', 'F16', '0.5015625', '0.43600478468899523', '0.9171875', '0.819377990430622']
['017c44c4dc365ec23fff7ac6bda62d70.jpg', 'F35', '0.8897727272727273', '0.615909090909091', '0.15227272727272728', '0.08068181818181819']
['017c44c4dc365ec23fff7ac6bda62d70.jpg', 'F35', '0.12926136363636365', '0.571875', '0.17102272727272727', '0.09261363636363637']
['017e4cb7ca8ff5856dcbfeb664346527.jpg', 'Mirage2000', '0.4846082089552239', '0.6980337078651685', '0.19916044776119404', '0.3082865168539326']
['017f77f4fb856120d054a4b9f4f1e4ae.jpg', 'AV8B', '0.4725', '0.16369710467706014', '0.375', '0.24276169265033407']
['017fe119f88f70c68b0dd9d4bae77845.jpg', 'F35', '0.5043333333333333', '0.533', '0.41', '0.368']
['01835356ae79102991c9974d480d3c92.jpg', 'E2', '0.5708955223880597', '0.4633075842696629', '0.08675373134328358', '0.34445224719101125']
['018a7f386182f9d145034d6dfe8007d1.jpg', 'J10', '0.28177083333333336', '0.54140625', '0.16145833333333334', '0.0859375']
['018a7f386182f9d145034d6dfe8007d1.jpg', 'J10', '0.5317708333333333', '0.59609375', '0.159375', '0.0859375']
['018a7f386182f9d145034d6dfe8007d1.jpg', 'J10', '0.33489583333333334', '0.6203125', '0.15729166666666666', '0.084375']
['018a7f386182f9d145034d6dfe8007d1.jpg', 'J10', '0.109375', '0.4140625', '0.16875', '0.0875']
['018a7f386182f9d145034d6dfe8007d1.jpg', 'J10', '0.37552083333333336', '0.70078125', '0.153125', '0.0828125']
['018a7f386182f9d145034d6dfe8007d1.jpg', 'J10', '0.7619791666666667', '0.60390625', '0.159375', '0.0859375']
['018be2d334e487da479adb3eb43eff82.jpg', 'Mirage2000', '0.769775390625', '0.2892030848329049', '0.44873046875', '0.23307626392459296']
['018be2d334e487da479adb3eb43eff82.jpg', 'EF2000', '0.283935546875', '0.2866323907455013', '0.44775390625', '0.26735218508997427']
['018f9df9e1087c69a2fccde8c1a36594.jpg', 'Tu95', '0.5749289772727273', '0.43986742424242425', '0.6697443181818182', '0.6183712121212122']
['019754939949887e2b08b54cf9c69afe.jpg', 'F35', '0.5241358760429082', '0.5818862275449102', '0.8853794199443782', '0.5907185628742515']
['0199df62a391865326a5150d525e702f.jpg', 'Rafale', '0.4874267578125', '0.12321493958257049', '0.048583984375', '0.049432442328817286']
['0199df62a391865326a5150d525e702f.jpg', 'Rafale', '0.683349609375', '0.12467960454046137', '0.048828125', '0.05016477480776273']
['0199df62a391865326a5150d525e702f.jpg', 'E2', '0.5843505859375', '0.08147198828268033', '0.119873046875', '0.06114976199194434']
['019eb892b079c917fb4ce69408caa303.jpg', 'F35', '0.5120370370370371', '0.5458333333333333', '0.3055555555555556', '0.42685185185185187']
['019f7906eb4c9cb55d26eaf85a55c888.jpg', 'F117', '0.52885443583118', '0.534912109375', '0.07751937984496124', '0.03173828125']
['01a8c20ab6d9eb48dff388dadae04367.jpg', 'Mirage2000', '0.4351679104477612', '0.5021067415730337', '0.11007462686567164', '0.12078651685393259']
['01a9c84cf8d5523da74a5a3e3ddc535f.jpg', 'Rafale', '0.8682', '0.5368926214757048', '0.1428', '0.07918416316736653']
['01a9c84cf8d5523da74a5a3e3ddc535f.jpg', 'Rafale', '0.2376', '0.5899820035992801', '0.1368', '0.07738452309538092']
['01a9c84cf8d5523da74a5a3e3ddc535f.jpg', 'A400M', '0.5554', '0.42231553689262147', '0.534', '0.21955608878224356']
['01ac65af6d3effdfe085aaaacc4caf08.jpg', 'MQ9', '0.2371875', '0.8075842696629213', '0.059375', '0.05711610486891386']
['01b296b342b0a2a61628bedc371aca6c.jpg', 'B1', '0.7445068359375', '0.6985321100917431', '0.126220703125', '0.050275229357798164']
['01b296b342b0a2a61628bedc371aca6c.jpg', 'B1', '0.0367431640625', '0.7324770642201834', '0.072998046875', '0.03302752293577982']
['01b296b342b0a2a61628bedc371aca6c.jpg', 'B1', '0.5001220703125', '0.4234862385321101', '0.999755859375', '0.8462385321100917']
['01b453062e65546fc504dfb90581daf0.jpg', 'F14', '0.8983333333333333', '0.7053333333333334', '0.1738095238095238', '0.15333333333333332']
['01b453062e65546fc504dfb90581daf0.jpg', 'C5', '0.4092857142857143', '0.45966666666666667', '0.8176190476190476', '0.7806666666666666']
['01b50c737e8bc7197267f7ffc0dd3940.jpg', 'F15', '0.5222222222222223', '0.3491666666666667', '0.23666666666666666', '0.15666666666666668']
['01b9cf540f93038af148ceeb14a17041.jpg', 'B52', '0.10388716890264878', '0.5231252806466098', '0.1719986240110079', '0.13560844185002247']
['01b9cf540f93038af148ceeb14a17041.jpg', 'B52', '0.2046783625730994', '0.5491692860350247', '0.20295837633298933', '0.14997754827121687']
['01b9cf540f93038af148ceeb14a17041.jpg', 'B52', '0.36721706226350187', '0.6064211944319713', '0.24527003783969728', '0.18724741805118994']
['01b9cf540f93038af148ceeb14a17041.jpg', 'B52', '0.4055727554179567', '0.439380332285586', '0.17956656346749225', '0.13246519982038618']
['01b9cf540f93038af148ceeb14a17041.jpg', 'B52', '0.6367389060887513', '0.49595868881903904', '0.2222222222222222', '0.17736865738661878']
['01b9cf540f93038af148ceeb14a17041.jpg', 'B52', '0.7858617131062952', '0.520655590480467', '0.2521499828001376', '0.1971261787157611']
['01b9cf540f93038af148ceeb14a17041.jpg', 'B52', '0.6761265909872721', '0.28962730130220027', '0.19298245614035087', '0.1400987876066457']
['01b9cf540f93038af148ceeb14a17041.jpg', 'B52', '0.8634330925352597', '0.27436012572968116', '0.2222222222222222', '0.16344858554108666']
['01bcc619b9718462686821a90ba7f5dc.jpg', 'F35', '0.40925925925925927', '0.5291666666666667', '0.5648148148148148', '0.19166666666666668']
['01c1ba8e9a4d1a39669ba8dd1689dacc.jpg', 'F4', '0.4108367626886145', '0.4583333333333333', '0.6735253772290809', '0.3194444444444444']
['01c1bbe086ccd2a86ff839287bb7d7e6.jpg', 'YF23', '0.7796875', '0.8776041666666666', '0.440625', '0.24479166666666666']
['01c1bbe086ccd2a86ff839287bb7d7e6.jpg', 'YF23', '0.3453125', '0.3697916666666667', '0.6796875', '0.70625']
['01cc16d38c49a3ecc2aec7f12a6a0656.jpg', 'F35', '0.5231400117164616', '0.8484375', '0.5951962507322789', '0.1921875']
['01ccb857a1933b7f869232dbe4ac83b8.jpg', 'US2', '0.6169753086419754', '0.6097222222222223', '0.7475308641975309', '0.649074074074074']
['01df2c628fb34c5393240760f8192615.jpg', 'C2', '0.5005555555555555', '0.5375', '0.9988888888888889', '0.7483333333333333']
['01df70fc8d7d21e10be2655935421043.jpg', 'XB70', '0.4955595026642984', '0.4700665188470067', '0.9413854351687388', '0.3458980044345898']
['01dfc1161077886eab0fcfa7dd73bae2.jpg', 'F14', '0.75625', '0.44670846394984326', '0.4375', '0.45768025078369906']
['01e4d99acc4167f2f5b3b63102c80019.jpg', 'F18', '0.4306640625', '0.2202970297029703', '0.638671875', '0.2995049504950495']
['01e4d99acc4167f2f5b3b63102c80019.jpg', 'F4', '0.53662109375', '0.5686881188118812', '0.8876953125', '0.4591584158415842']
['01ec1bf3a71092f2c9cfe3bf34135ae4.jpg', 'US2', '0.4775390625', '0.4175347222222222', '0.13720703125', '0.1015625']
['01ed4d81c5d733cbaa266b6ea7821254.jpg', 'A10', '0.77294921875', '0.451312045526399', '0.17724609375', '0.059121087575086946']
['01eec1ab0a324ad589c8966ef232abc5.jpg', 'A400M', '0.45588235294117646', '0.41956521739130437', '0.5470588235294118', '0.2608695652173913']
['01f383d5b982cf4a9b7de72d47247048.jpg', 'Rafale', '0.3506', '0.6373197115384616', '0.1404', '0.08954326923076923']
['01fc38f911bdae9d15d4e7373c6394ed.jpg', 'B52', '0.7493925720236029', '0.21499219156689225', '0.04442901770218674', '0.03331598125976054']
['01fc38f911bdae9d15d4e7373c6394ed.jpg', 'B52', '0.8630683790350573', '0.2553357626236335', '0.04477611940298507', '0.027589796980739198']
['02005cad192382d6bc9daf4528ba4682.jpg', 'F15', '0.5001666666666666', '0.5232501223690651', '0.9996666666666667', '0.8908467939304944']
['02013d7accc296d5d52bc297dfa760c6.jpg', 'JAS39', '0.46938775510204084', '0.4009259259259259', '0.9375386518243661', '0.8']
['020653810498d88bb5c0128b69ad2f42.jpg', 'SR71', '0.4780439121756487', '0.45515394912985274', '0.8043912175648703', '0.17402945113788487']
['02077e52bc18c0b141ddcb213dc4548e.jpg', 'B1', '0.499375', '0.5025906735751295', '0.20958333333333334', '0.08290155440414508']
['020af567493f537753d55ea9952be4c0.jpg', 'SR71', '0.521875', '0.5274163568773235', '0.71875', '0.32806691449814124']
['020eaf5e1e54dc48d9278cf58e5d0afa.jpg', 'B1', '0.38666666666666666', '0.2945619335347432', '0.04833333333333333', '0.1027190332326284']
['020eaf5e1e54dc48d9278cf58e5d0afa.jpg', 'B2', '0.4345833333333333', '0.24471299093655588', '0.060833333333333336', '0.054380664652567974']
['020eaf5e1e54dc48d9278cf58e5d0afa.jpg', 'B52', '0.5154166666666666', '0.31268882175226587', '0.0675', '0.11178247734138973']
['020f5a36dde26e70f0b8de4fc5020eb6.jpg', 'JAS39', '0.4204861111111111', '0.5208333333333334', '0.2798611111111111', '0.2']
['021a559b6c0aa0ef049d86e27a1f6804.jpg', 'Su34', '0.4796779141104294', '0.4557216791259344', '0.02147239263803681', '0.06382978723404255']

In [10]:
# convert labels from csv to json
df = pd.read_csv(path_train_img/'metadata.csv')
df.to_json(path_train_img/'metadata.json', orient='records')

In [11]:
df.head()

,file_name,label,x_center,y_center,width,height
0,00032844ab679240fc03ecd27d29a6aa.jpg,F18,0.516725,0.388498,0.966549,0.758216
1,0003f56298fa8999168d7988a2e9549d.jpg,F22,0.465027,0.394512,0.824765,0.414535
2,0003f56298fa8999168d7988a2e9549d.jpg,F22,0.556846,0.441231,0.886307,0.464961
3,000aa01b25574f28b654718db0700f72.jpg,F35,0.695801,0.249084,0.559570,0.238828
4,000aa01b25574f28b654718db0700f72.jpg,JAS39,0.175293,0.608791,0.185547,0.090842

In [13]:
df.corr(numeric_only=True)

          x_center  y_center     width    height
x_center  1.000000 -0.036734  0.040943  0.020795
y_center -0.036734  1.000000  0.067405  0.082335
width     0.040943  0.067405  1.000000  0.794870
height    0.020795  0.082335  0.794870  1.000000